// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj7axA_nG3J8C-zrvtnkYU7hgSN-KyRTw',
    appId: '1:506707135077:web:e072e4c5edbdea4d22148c',
    messagingSenderId: '506707135077',
    projectId: 'githubmcp-50439',
    authDomain: 'githubmcp-50439.firebaseapp.com',
    storageBucket: 'githubmcp-50439.firebasestorage.app',
    measurementId: 'G-DEWTZ4ZDB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ATqqPqwd-D_RJFjhUyN4imU4MqMR3gw',
    appId: '1:506707135077:android:a9b029282043437822148c',
    messagingSenderId: '506707135077',
    projectId: 'githubmcp-50439',
    storageBucket: 'githubmcp-50439.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcqpQsZ1HZ8-Cw9v1YewNsXL2AuQRiKDI',
    appId: '1:506707135077:ios:eeb10ea7037b667c22148c',
    messagingSenderId: '506707135077',
    projectId: 'githubmcp-50439',
    storageBucket: 'githubmcp-50439.firebasestorage.app',
    iosClientId: '506707135077-ugtjligf4esqida79ooj03ad8mel729e.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcqpQsZ1HZ8-Cw9v1YewNsXL2AuQRiKDI',
    appId: '1:506707135077:ios:eeb10ea7037b667c22148c',
    messagingSenderId: '506707135077',
    projectId: 'githubmcp-50439',
    storageBucket: 'githubmcp-50439.firebasestorage.app',
    iosClientId: '506707135077-ugtjligf4esqida79ooj03ad8mel729e.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj7axA_nG3J8C-zrvtnkYU7hgSN-KyRTw',
    appId: '1:506707135077:web:a857f4475b9c3d4522148c',
    messagingSenderId: '506707135077',
    projectId: 'githubmcp-50439',
    authDomain: 'githubmcp-50439.firebaseapp.com',
    storageBucket: 'githubmcp-50439.firebasestorage.app',
    measurementId: 'G-6EWYDQQB3S',
  );
}
